import commonjs from '@rollup/plugin-commonjs'
import terser from '@rollup/plugin-terser'
import nodePolyfills from 'rollup-plugin-polyfill-node'
import { nodeResolve } from '@rollup/plugin-node-resolve'
import external from 'rollup-plugin-peer-deps-external'
import json from '@rollup/plugin-json'
import builtins from 'builtin-modules'

export default {
  input: 'src/index.js',
  output: {
    dir: 'C:/codespace/obplus/build/1.obplus/dist',
    // dir: 'C:\\codespace\\obplus\\fastify_v4\\server\\output',
    // file: 'C:\\codespace\\obplus\\fastify_v4\\server\\output\\index.js',
    //   format: 'es',
    // name: 'obplus',
    sourcemap: false,
    format: 'cjs',
    // external: [
    //   'dayjs',
    //   'node-schedule',
    //   'fastify',
    //   '@fastify/cors',
    //   '@fastify/multipart',
    //   '@fastify/rate-limit',
    //   '@fastify/formbody',
    //   '@fastify/jwt',
    //   '@fastify/static',
    //   'dotenv',
    //   'graceful-fs',
    //   'lodash',
    //   'knex',
    //   'ua-parser-js',
    //   'jsonwebtoken',
    //   'bcrypt',
    //   'base64-img',
    //   'sharp',
    //   'winston',
    //   'cacheable',
    //   'axios',
    // ],
    // inlineDynamicImports: true,
  },
  plugins: [
    // nodePolyfills(),
    nodeResolve({ preferBuiltins: true }),
    commonjs(),
    json({ compact: true }),
    external({ includeDependencies: true, packageJsonPath: './package.json' }),
    terser(),
  ],
  external: [
    ...builtins,
    'mock-aws-s3',
    'aws-sdk',
    'nock',
    'mysql',
    'sqlite3',
    'better-sqlite3',
    'mysql2',
    'pg',
    'pg-query-stream',
    'oracledb',
  ],
  // external: [
  //   ...builtins,
  //   'dayjs',
  //   'node-schedule',
  //   'fastify',
  //   '@fastify/cors',
  //   '@fastify/multipart',
  //   '@fastify/rate-limit',
  //   '@fastify/formbody',
  //   '@fastify/jwt',
  //   '@fastify/static',
  //   'dotenv',
  //   'graceful-fs',
  //   'lodash',
  //   'knex',
  //   'ua-parser-js',
  //   'jsonwebtoken',
  //   'bcrypt',
  //   'base64-img',
  //   'sharp',
  //   'winston',
  //   'cacheable',
  //   'axios',
  // ],
  // external: [
  //   'dayjs',
  //   'node-schedule',
  //   'fastify',
  //   '@fastify/cors',
  //   '@fastify/multipart',
  //   '@fastify/rate-limit',
  //   '@fastify/formbody',
  //   '@fastify/jwt',
  //   '@fastify/static',
  //   'dotenv',
  //   'graceful-fs',
  //   'lodash',
  //   'knex',
  //   'ua-parser-js',
  //   'jsonwebtoken',
  //   'bcrypt',
  //   'base64-img',
  //   'sharp',
  //   'winston',
  //   'cacheable',
  //   'axios',
  // ],
}
